name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  verification:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run all tests
        run: sudo ./gradlew test
