name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  verification:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'

      - name: verify code style
        run: sudo ./gradlew ktlintCheck

      - name: Run all tests
        run: sudo ./gradlew test
