name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: verify code style
        run: sudo ./gradlew ktlintCheck

      - name: Run all tests
        run: sudo ./gradlew test

      - name: Save test reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: 'build/reports/tests/test/'
